name: Validate master

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: cloud-storage-master-${{ github.ref }}
  cancel-in-progress: false

jobs:
  validate:
    uses: ./.github/workflows/validate-go.yml
