name: Validate pull request

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: cloud-storage-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/validate-go.yml
